apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-apps
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx-apps
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: nginx-apps
   spec:
     containers:
     - image: registry.eu-west-0.prod-cloud-ocb.orange-business.com/ernest/nginx-custom-image:latest
       imagePullPolicy: Always
       name: nginx-apps
       resources:
        limits:
        requests:
          cpu: '2'
       env:
       command:
       volumeMounts:


     imagePullSecrets:
       - name: default-secret
     volumes:
     - name: pvc-data
       persistentVolumeClaim:
         claimName: cce-sfs-nhe-cce-pvc4
